Add missing command to using-openaps-tools.md
`openaps use tz rezone ...` will fail if the report hasn't been invoked yet:
```
argparse.ArgumentTypeError: can't open 'raw-cgm/glucose-raw.json': [Errno 2] No such file or directory: 'raw-cgm/glucose-raw.json'
```